define(function(require) {
    var ExtendedModel = require('componentLibrary-Utils/ExtendedBackboneModel');

    return ExtendedModel.extend({
        defaults: {
            showBulletPath: true,
            firedBullets: 0,
            showBulletsLeft: false,
            maximumBullets: 99,
            yVelocityAfter10sec: 0,
            radiusOfCurvature: 0,
            ballX: 0,
            ballY: 0,
            lockSimAfterDestroy: false,
            lockSim: false,
            enableFireButton: true,
            showBulletGhost: true,
            showBulletAccelerationVector: false,
            showBulletVelocityVector: false,
            vx : {x: 0, y: 0},
            vy : {x: 0, y: 0},
            timeOfFlight: 0,
            initialXVelocity: 0,
            initialYVelocity: 0,
            distanceTravelled: 0,
            ballVisible: false
        },

        getShowBulletPath: function() { return this.get('showBulletPath'); },
        setShowBulletPath: function(value) { this.set('showBulletPath', value); },
        getFiredBullets: function() { return this.get('firedBullets'); },
        setFiredBullets: function(value) { this.set('firedBullets', value); },
        getShowBulletsLeft: function() { return this.get('showBulletsLeft'); },
        setShowBulletsLeft: function(value) { this.set('showBulletsLeft', value); },
        getMaximumBullets: function() { return this.get('maximumBullets'); },
        setMaximumBullets: function(value) { this.set('maximumBullets', value); },
        getYVelocityAfter10sec: function(){ return this.get('yVelocityAfter10sec');},
        setYVelocityAfter10sec: function(value) { this.set('yVelocityAfter10sec', value); },
        getRadiusOfCurvature: function(){ return this.get('radiusOfCurvature');},
        setRadiusOfCurvature: function(value) { this.set('radiusOfCurvature', value); },
        getEnableFireButton: function() { return this.get('enableFireButton'); },
        setEnableFireButton: function(value) { this.set('enableFireButton', value); },
        getBallX: function() { return this.get('ballX'); },
        setBallX: function(value) { this.set('ballX', value); },
        getBallY: function() { return this.get('ballY'); },
        setBallY: function(value) { this.set('ballY', value); },
        getLockSim: function() { return this.get('lockSim'); },
        setLockSim: function(value) { this.set('lockSim', value); },
        getLockSimAfterDestroy: function() { return this.get('lockSimAfterDestroy'); },
        setLockSimAfterDestroy: function(value) { this.set('lockSimAfterDestroy', value); },
        getTimeOfFlight: function() { return this.get('timeOfFlight'); },
        setTimeOfFlight: function(value) { this.set('timeOfFlight', value); },
        getInitialXVelocity: function(){ return this.get('initialXVelocity');},
        setInitialXVelocity: function(value) { this.set('initialXVelocity', value); },
        getInitialYVelocity: function(){ return this.get('initialYVelocity');},
        setInitialYVelocity: function(value) { this.set('initialYVelocity', value); },
        getDistanceTravelled: function(){ return this.get('distanceTravelled');},
        setDistanceTravelled: function(value) { this.set('distanceTravelled', value); },
        getBallVisible: function(){ return this.get('ballVisible');},
        setBallVisible: function(value) { this.set('ballVisible', value); }
    });
});