define(function(require){
    return {
        'ui/htmlRenderer': require('componentLibrary-Renderers/HtmlRenderer'),
        'ui/textRenderer': require('componentLibrary-Renderers/TextRenderer'),
        'ui/templateRenderer': require('componentLibrary-Renderers/TemplateRenderer'),
        'ui/draggable' : require('componentLibraryJQueryUI/Draggable'),
        'ui/aimPath': require('lib/ui/AimPath'),
        'ui/anglePath': require('lib/ui/AnglePath'),
        'ui/drawPath': require('lib/ui/DrawPath'),
        'ui/drawLine': require('lib/ui/DrawLine'),

        'behaviour/createCannonBall': require('lib/behaviour/CreateCannonBall'),
        'behaviour/updateBall': require('lib/behaviour/UpdateBall'),
        'behaviour/updateFiredBullets': require('lib/behaviour/UpdateFiredBullets'),
        'behaviour/updateBulletsLeft': require('lib/behaviour/UpdateBulletsLeft'),
        'behaviour/createTarget': require('lib/behaviour/CreateTarget'),
        'behaviour/dragTarget': require('lib/behaviour/DragTarget'),
        'behaviour/targetCollision': require('lib/behaviour/TargetCollision'),
        'behaviour/destroyTarget': require('lib/behaviour/DestroyTarget'),
        'behaviour/chipTarget': require('lib/behaviour/ChipTarget'),
        'behaviour/lockDraggable': require('lib/behaviour/LockDraggable'),
        'behaviour/updateVectors': require('lib/behaviour/UpdateVectors'),
        'behaviour/updateDistance': require('lib/behaviour/UpdateDistance'),
        'behaviour/aimHandle': require('lib/behaviour/AimHandle'),
        'behaviour/tooltipPositioner': require('lib/behaviour/TooltipPositioner'),
        'behaviour/tooltipCreator': require('lib/behaviour/TooltipCreator'),
        'behaviour/createTooltip': require('lib/behaviour/CreateTooltip'),

        'model/cannonBall': require('lib/model/CannonBall'),
        'model/inputValue': require('lib/model/InputValue'),
        'model/cannon': require('lib/model/Cannon'),
        'model/targets': require('lib/model/Targets'),
        'model/target': require('lib/model/Target'),
        'model/aim': require('lib/model/Aim'),

        'capi/inputValue': require('lib/capi/InputValue'),
        'capi/cannon': require('lib/capi/Cannon'),
        'capi/targets': require('lib/capi/Targets'),
        'capi/target': require('lib/capi/Target'),
        'capi/aim': require('lib/capi/Aim'),

        'sync/modelToInput': require('componentLibrary-Sync/ModelToInput'),
        'sync/toggleVisibility': require('componentLibrary-Sync/ToggleVisibility'),
        'sync/toggleClass': require('componentLibrary-Sync/ToggleClass'),
        'sync/modelToModel': require('componentLibrary-Sync/ModelToModel'),
        'sync/modelToText': require('componentLibrary-Sync/ModelToText'),
        'sync/modelToNumericProperty': require('componentLibrary-Sync/ModelToNumericProperty'),
        'sync/toggleProperty': require('componentLibrary-Sync/ToggleProperty'),
        'sync/setOnEvent': require('componentLibrary-Sync/SetOnEvent'),
        'sync/modelToProperty': require('componentLibrary-Sync/ModelToProperty'),

        'sync/draggableToModel': require('lib/sync/DraggableToModel'),
        'sync/angleInput': require('lib/sync/AngleInput'),
        'sync/velocityInput': require('lib/sync/VelocityInput'),
        'sync/lockSim': require('lib/sync/LockSim'),
        'sync/cannon': require('lib/sync/Cannon'),
        'sync/flight': require('lib/sync/Flight'),
        'sync/toggleRendererProperty': require('lib/sync/ToggleRendererProperty'),

        'validator/number': require('lib/validator/Number'),
        'validator/range': require('lib/validator/Range'),
        'validator/aimPosition': require('lib/validator/AimPosition'),
        'validator/targetPosition': require('lib/validator/TargetPosition')
    };
});
